"""empty message

Revision ID: 79ba52d901f7
Revises: e5d24140d4c8
Create Date: 2022-05-07 20:13:53.184145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ba52d901f7'
down_revision = 'e5d24140d4c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('genre_db', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_book_genre_db'), 'book', ['genre_db'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_genre_db'), table_name='book')
    op.drop_column('book', 'genre_db')
    # ### end Alembic commands ###
